apiVersion: v1alpha1
kind: Fleet
metadata:
  name: basic-nginx-fleet
spec:
  selector:
    matchLabels:
      fleet: basic-nginx-fleet
  template:
    spec:
      os:
        image: harbor.nsx.techlab.netone.co.jp/bootc/microshift-4.17-bootc:v1.0
      config:
        - name: motd-update
          inline:
            - path: "/etc/motd"
              content: "This system is managed by flightctl."
              mode: 0644
        - name: authorized-keys
          inline:
            - path: "/root/.ssh/authorized_keys"
              content: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvlKyJ1gK8v4YGl12hmz1Mq1QnA0FHnMgFD6dA0K/dKYM0uBlg/XtNH9G9xtoK7ifM1rK43pi0P7iQ7r9QNQIlggztrsYPMMjtGXt5R4Z8B5jWNIjQn4rAMghZbck016PJQ6P3R4787MXuZi339F/lP6FvA81el4Fm4aIVv5bbWyYWMjQ2aQDQb2zGh/GWYervcmV3+jjTK5MQzLOd70W5OIggicafze0dIWbLay9ks+5fGqX7klre8ZhOFWME806gJPoBjtfteD9RQ9Fgxio01gf8FuJSfhsuSz831nVmx7A6jjTGa3ExnVB1SCERyJoC5DjLeU4XmOAOozSfYYypnMHYoBhVvWGpYzHFEauUlekzJ30WBnMTXMqU7tg6LuQtL7RG329VCDvNy3/aHhb4NM4n79TB1v+s49yP6XxciuHeHK5VgqIG3D72LFS2+EM7bO8Y9onqgIXWB/DOh4mKroKBE8o3Tb9sPhX3C8xLZGkebTGW8kbcwIvd4pXUHVk="
              mode: 0644
        - name: microshift-manifests
          gitRef:  
            repository: flightctl-demo
            targetRevision: main
            path: /demos/basic-nginx-demo/configuration
      systemd:
        matchPatterns:
          - "flightctl-agent.service"
